name: Webflow CMS SEO Audit

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Webflow CMS Items
        run: |
          curl -X GET "https://api.webflow.com/v2/collections/667fa51fcaf992f6b85b7db5e/items" \
          -H "Authorization: Bearer ${{ secrets.WEBFLOW_API_TOKEN }}" \
          -H "accept: application/json" \
          -o items.json

      - name: Run SEO Audit
        run: |
          python3 analyse.py

      - name: Afficher le rapport
        run: |
          cat rapport.md
